// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vddwjpsfsrediciemabz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZHdqcHNmc3JlZGljaWVtYWJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDM2MDcsImV4cCI6MjA3MDExOTYwN30.xODQ8ut7VaXJ-WeB_rcSBTAY_Xm2ySMmzDApOmUhBg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});